# Generated by Django 5.1.1 on 2024-09-21 00:18

import django.core.validators
import producto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_minima',
            field=models.IntegerField(default=0, validators=[producto.models.validar_rango]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=8, validators=[producto.models.validar_codigo]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=200, validators=[producto.models.validar_descripcion]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=80, validators=[producto.models.validar_nombre]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(999.0)]),
        ),
    ]
