# Generated by Django 5.1.1 on 2024-09-21 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_producto_cantidad_minima_alter_producto_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(999.0)]),
        ),
    ]
